import { normalizeText } from './normalize';

export type RoomElements = ReturnType<typeof selectRoomElements>;

export const selectRoomElements = (root: HTMLElement) => {
  const isRuntimeElement = (node: Element) => !node.closest('#musiki-pod-templates');
  const queryAll = <T extends Element = Element>(selector: string) => {
    const all = Array.from(root.querySelectorAll<T>(selector));
    const runtime = all.filter(isRuntimeElement);
    return runtime.length > 0 ? runtime : all;
  };
  const query = <T extends Element = Element>(selector: string) => queryAll<T>(selector)[0] || null;

  const audioInputSelects = queryAll<HTMLSelectElement>('[data-audio-input-select]').filter(
    (node): node is HTMLSelectElement => node instanceof HTMLSelectElement,
  );
  const videoInputSelects = queryAll<HTMLSelectElement>('[data-video-input-select]').filter(
    (node): node is HTMLSelectElement => node instanceof HTMLSelectElement,
  );
  const midiInputSelects = queryAll<HTMLSelectElement>('[data-midi-input-select]').filter(
    (node): node is HTMLSelectElement => node instanceof HTMLSelectElement,
  );

  return {
    roomInput: root.querySelector('[data-room-input]'),
    identityInput: root.querySelector('[data-identity-input]'),
    nameInput: root.querySelector('[data-name-input]'),
    roleInput: root.querySelector('[data-role-input]'),
    roleLabel: root.querySelector('[data-role-label]'),
    layoutInput: root.querySelector('[data-layout-input]'),
    audioInputSelects,
    videoInputSelects,
    midiInputSelects,
    audioInputSelect: audioInputSelects[0] || null,
    videoInputSelect: videoInputSelects[0] || null,
    midiInputSelect: midiInputSelects[0] || null,
    presentationSelect: query('[data-presentation-select]'),
    sessionSetupDetails: root.querySelector('[data-session-setup]'),
    previewZoomInput: root.querySelector('[data-preview-zoom-input]'),
    previewZoomOutput: root.querySelector('[data-preview-zoom-output]'),
    previewZoomSidebarInput: root.querySelector('[data-preview-zoom-sidebar-input]'),
    previewZoomSidebarOutput: root.querySelector('[data-preview-zoom-sidebar-output]'),
    circleSizeInput: root.querySelector('[data-circle-size-input]'),
    circleSizeOutput: root.querySelector('[data-circle-size-output]'),
    gridSizeInput: root.querySelector('[data-grid-size-input]'),
    backgroundBlurToggleButton: root.querySelector('[data-action="background-blur-toggle"]'),
    backgroundReplaceToggleButton: root.querySelector('[data-action="background-replace-toggle"]'),
    backgroundReplacePopup: root.querySelector('[data-background-replace-popup]'),
    backgroundReplaceCloseButton: root.querySelector('[data-action="background-replace-close"]'),
    backgroundEffectClearButton: root.querySelector('[data-action="background-effect-clear"]'),
    backgroundImagePreviewShell: root.querySelector('[data-background-image-preview-shell]'),
    backgroundImagePreview: root.querySelector('[data-background-image-preview]'),
    backgroundImageLabel: root.querySelector('[data-background-image-label]'),
    backgroundImageClearButton: root.querySelector('[data-action="background-image-clear"]'),
    backgroundImageFileInput: root.querySelector('[data-background-image-file-input]'),
    backgroundImageDropzone: root.querySelector('[data-background-image-dropzone]'),
    backgroundImagePickButton: root.querySelector('[data-action="background-image-pick"]'),
    backgroundImageSearchInput: root.querySelector('[data-background-image-search-input]'),
    backgroundImageSearchButton: root.querySelector('[data-action="background-image-search"]'),
    backgroundImageStatus: root.querySelector('[data-background-image-status]'),
    backgroundImageResults: root.querySelector('[data-background-image-results]'),
    backgroundColorInput: root.querySelector('[data-background-color-input]'),
    backgroundColorApplyButton: root.querySelector('[data-action="background-color-apply"]'),
    previewInvertInput: root.querySelector('[data-preview-invert-input]'),
    showCircleInput: root.querySelector('[data-show-circle-input]'),
    statusNode: root.querySelector('[data-room-status]'),
    stateNode: root.querySelector('[data-room-state]'),
    countNode: root.querySelector('[data-participant-count]'),
    connectToggleButton: root.querySelector('[data-action="connect-toggle"]'),
    connectButton: root.querySelector('[data-action="connect"]'),
    disconnectButton: root.querySelector('[data-action="disconnect"]'),
    cameraButton: root.querySelector('[data-action="camera"]'),
    microphoneButton: root.querySelector('[data-action="microphone"]'),
    micMeter: root.querySelector('[data-mic-meter]'),
    shareScreenButton: root.querySelector('[data-action="screen-share"]'),
    presentationButton: root.querySelector('[data-action="presentation"]'),
    presentationClearButton: root.querySelector('[data-action="presentation-clear"]'),
    layoutChoiceButtons: Array.from(root.querySelectorAll('[data-layout-choice]')),
    audioInputPanel: root.querySelector('[data-audio-input-panel]'),
    videoInputPanel: root.querySelector('[data-video-input-panel]'),
    teacherSlot: query<HTMLElement>('[data-slot="teacher"]'),
    gridSlot: query<HTMLElement>('[data-slot="grid"]'),
    studentsSlot: query<HTMLElement>('[data-slot="students"]'),
    screenSlot: query<HTMLElement>('[data-slot="screen"]'),
    circleSlot: query<HTMLElement>('[data-slot="circle"]'),
    floatingCircleWrap: root.querySelector('[data-floating-circle]'),
    identityPreviewSlot: root.querySelector('[data-slot="identity-preview"]'),
    teacherPanel: root.querySelector('[data-panel="teacher"]'),
    participantList: query('[data-participant-list]'),
    participantLists: queryAll<HTMLElement>('[data-participant-list]').filter(
      (node): node is HTMLElement => node instanceof HTMLElement,
    ),
    stage: root.querySelector('[data-stage]'),
    stageFrameNode: root.querySelector('.conference-stage-frame'),
    gravityBallCanvas: root.querySelector('[data-gravity-ball-canvas]'),
    recordingGuide: root.querySelector('[data-recording-guide]'),
    reactionsLayer: root.querySelector('[data-reactions-layer]'),
    stageHandOverlay: root.querySelector('[data-stage-hand-overlay]'),
    participantTemplate: root.querySelector('[data-template="participant-card"]'),
    screenTemplate: root.querySelector('[data-template="screen-card"]'),
    presentationFrame: query('[data-presentation-frame]'),
    presentationPlaceholder: query('[data-presentation-placeholder]'),
    liveActivityButton: root.querySelector('[data-live-activity-button]'),
    liveActivityTimer: root.querySelector('[data-live-activity-timer]'),
    sessionTimer: root.querySelector('[data-session-timer]'),
    recordButton: root.querySelector('[data-action="record"]'),
    fullscreenButton: root.querySelector('[data-action="fullscreen"]'),
    kickToggleButton: root.querySelector('[data-action="session-kick-toggle"]'),
    shortcutsHelpButton: root.querySelector('[data-action="shortcuts-help"]'),
    sidebarToggleButton: root.querySelector('[data-action="sidebar-toggle"]'),
    instrumentsToggleButton: root.querySelector('[data-action="instruments-toggle"]'),
    shortcutsModal: root.querySelector('[data-shortcuts-modal]'),
    shortcutsCloseButton: root.querySelector('[data-shortcuts-close]'),
    setupModal: root.querySelector('[data-setup-modal]'),
    setupModalCloseButton: root.querySelector('[data-setup-close]'),
    setupModalTriggerButton: root.querySelector('[data-action="setup-modal-toggle"]'),
    setupSearchInput: root.querySelector('[data-setup-search]'),
    welcomeModal: root.querySelector('[data-welcome-modal]'),
    welcomeVideoPreview: root.querySelector('[data-welcome-video-preview]'),
    welcomeVumeter: root.querySelector('[data-welcome-vumeter]'),
    welcomeMicSelect: root.querySelector('[data-welcome-mic-select]'),
    welcomeCamSelect: root.querySelector('[data-welcome-cam-select]'),
    welcomeTestToggleButton: root.querySelector('[data-welcome-test-toggle]'),
    welcomeTestTimer: root.querySelector('[data-welcome-test-timer]'),
    welcomeJoinButton: root.querySelector('[data-welcome-join]'),
    welcomeOpenButton: root.querySelector('[data-action="welcome-modal-open"]'),
    externalInviteGate: root.querySelector('[data-external-invite-gate]'),
    externalInviteForm: root.querySelector('[data-external-invite-form]'),
    externalInviteCloseButton: root.querySelector('[data-external-invite-close]'),
    externalInviteNameInput: root.querySelector('[data-external-invite-name]'),
    externalInviteEmailInput: root.querySelector('[data-external-invite-email]'),
    externalInvitePasswordInput: root.querySelector('[data-external-invite-password]'),
    externalInviteGateStatus: root.querySelector('[data-external-invite-gate-status]'),
    externalInviteJoinButton: root.querySelector('[data-action="external-invite-join"]'),
    externalInviteTeacherPasswordInput: root.querySelector('[data-external-password-input]'),
    externalInviteExpirySelect: root.querySelector('[data-external-expiry-select]'),
    externalInviteLinkOutput: root.querySelector('[data-external-invite-link-output]'),
    externalInviteStatus: root.querySelector('[data-external-invite-status]'),
    externalInviteCreateButton: root.querySelector('[data-action="external-invite-create"]'),
    externalInviteCopyButton: root.querySelector('[data-action="external-invite-copy"]'),
    externalInviteRevokeButton: root.querySelector('[data-action="external-invite-revoke"]'),
    studentInviteExpirySelect: root.querySelector('[data-student-expiry-select]'),
    studentInviteLinkOutput: root.querySelector('[data-student-invite-link-output]'),
    studentInviteStatus: root.querySelector('[data-student-invite-status]'),
    studentInviteCreateButton: root.querySelector('[data-action="student-invite-create"]'),
    studentInviteCopyButton: root.querySelector('[data-action="student-invite-copy"]'),
    studentInviteRevokeButton: root.querySelector('[data-action="student-invite-revoke"]'),
    chatList: query('[data-chat-list]'),
    chatScroller: query('[data-chat-scroller]'),
    chatInput: query('[data-chat-input]'),
    chatSection: query('[data-chat-section]'),
    chatFocusButton: query('[data-action="chat-focus"]'),
    chatUnreadDot: query('[data-chat-unread]'),
    chatStatus: query('[data-chat-status]'),
    chatSendButton: query('[data-action="chat-send"]'),
    chatDownloadButton: query('[data-action="chat-download"]'),
    raiseHandButton: root.querySelector('[data-action="raise-hand"]'),
    handTrackInput: root.querySelector('[data-hand-track-input]'),
    handTrackToggleButton: root.querySelector('[data-hand-track-toggle]'),
    handRampInput: root.querySelector('[data-hand-ramp-input]'),
    gravityBallInput: root.querySelector('[data-gravity-ball-input]'),
    gravityBallToggleButton: root.querySelector('[data-gravity-ball-toggle]'),
    gravityBallGravityInput: root.querySelector('[data-gravity-ball-gravity-input]'),
    gravityBallMirrorInput: root.querySelector('[data-gravity-ball-mirror-input]'),
    synthMappingResetButton: root.querySelector('[data-synth-mapping-reset]'),
    recordingPresetSelect: root.querySelector('[data-recording-preset-select]'),
    sessionControlsField: root.querySelector('[data-session-controls-field]'),
    sessionAllowInstrumentsInput: root.querySelector('[data-session-allow-instruments-input]'),
    breakRoomsShell: root.querySelector('[data-break-rooms-shell]'),
    breakRoomsPopup: root.querySelector('[data-break-rooms-popup]'),
    breakRoomsPopupSetup: root.querySelector('[data-break-rooms-popup-setup]'),
    breakRoomsPopupDivider: root.querySelector('[data-break-rooms-popup-divider]'),
    breakRoomsList: root.querySelector('[data-break-rooms-list]'),
    breakRoomsStatusNote: root.querySelector('[data-break-rooms-status]'),
    breakRoomsSizeInput: root.querySelector('[data-break-rooms-size]'),
    breakRoomsCustomInputsContainer: root.querySelector('[data-break-rooms-custom-inputs]'),
    breakRoomsBBtn: root.querySelector('[data-break-rooms-btn]'),
    breakRoomsEndBtn: root.querySelector('[data-break-rooms-end-btn]'),
    breakRoomsKillBtn: root.querySelector('[data-break-rooms-kill-btn]'),
    externalMediaControlsShell: root.querySelector('[data-external-media-controls-shell]'),
    externalMediaBtn: root.querySelector('[data-external-media-btn]'),
    externalMediaPopup: root.querySelector('[data-external-media-popup]'),
    externalMediaInput: query('[data-external-media-input]'),
    externalMediaInputs: queryAll('[data-external-media-input]').filter((n): n is HTMLInputElement => n instanceof HTMLInputElement),
    externalMediaOpenButton: query('[data-action="external-media-open"]'),
    externalMediaOpenButtons: queryAll('[data-action="external-media-open"]'),
    externalMediaResults: query('[data-external-media-results]'),
    externalMediaResultsEls: queryAll('[data-external-media-results]').filter((n): n is HTMLElement => n instanceof HTMLElement),
    externalMediaStatus: query('[data-external-media-status]'),
    externalMediaStage: root.querySelector('[data-external-media-stage]'),
    externalMediaPlayerHost: root.querySelector('[data-external-media-player-host]'),
    externalMediaEmpty: root.querySelector('[data-external-media-empty]'),
    externalMediaTitle: root.querySelector('[data-external-media-title]'),
    externalMediaProviderLabel: root.querySelector('[data-external-media-provider-label]'),
    externalMediaPlayToggleButtons: Array.from(
      root.querySelectorAll('[data-action="external-media-play-toggle"]'),
    ),
    externalMediaCloseButtons: Array.from(
      root.querySelectorAll('[data-action="external-media-close"], [data-action="external-media-stop"]'),
    ),
    conceptsShell: root.querySelector('[data-concepts-shell]'),
    conceptsBtn: root.querySelector('[data-concepts-btn]'),
    conceptsPopup: root.querySelector('[data-concepts-popup]'),
    conceptSearchInput: query('[data-concept-search]'),
    conceptResults: query('[data-concept-results]'),
    conceptSearchInputs: queryAll('[data-concept-search]').filter((n): n is HTMLInputElement => n instanceof HTMLInputElement),
    conceptResultsEls: queryAll('[data-concept-results]').filter((n): n is HTMLElement => n instanceof HTMLElement),
    conceptFrame: root.querySelector('[data-concept-frame]'),
    conceptPlaceholder: root.querySelector('[data-concept-placeholder]'),
    whiteboardCanvas: query('[data-whiteboard-canvas]'),
    whiteboardBgCanvas: query('[data-whiteboard-bg-canvas]'),
    whiteboardToolbar: query('[data-whiteboard-toolbar]'),
    whiteboardBgButtons: queryAll('[data-whiteboard-bg-btn]'),
    panelCloseButtons: Array.from(root.querySelectorAll('[data-action="close-panel"]')),
    brCountdownEl: root.querySelector('[data-br-countdown]'),
    brCountdownText: root.querySelector('[data-br-countdown-text]'),
    sessionMuteAllButton: root.querySelector('[data-session-mute-all-button]'),
    recentSpeakersEls: Array.from(root.querySelectorAll('[data-recent-speakers]')),
    streamingProfileSelect: root.querySelector('[data-streaming-profile-select]'),
    optimizeSpeakerInput: root.querySelector('[data-optimize-speaker-input]'),
    limitGridQualityInput: root.querySelector('[data-limit-grid-input]'),
    audioEchoCancellationInput: root.querySelector('[data-audio-echo-cancellation-input]'),
    audioNoiseSuppressionInput: root.querySelector('[data-audio-noise-suppression-input]'),
    audioAutoGainControlInput: root.querySelector('[data-audio-auto-gain-control-input]'),
    fmLatencySelect: root.querySelector<HTMLSelectElement>('[data-fm-latency-select]'),
    fmSampleRateSelect: root.querySelector<HTMLSelectElement>('[data-fm-samplerate-select]'),
    synthCarrierInput: root.querySelector('[data-synth-carrier-input]'),
    synthCarrierOutput: root.querySelector('[data-synth-carrier-output]'),
    synthModulatorInput: root.querySelector('[data-synth-modulator-input]'),
    synthModulatorOutput: root.querySelector('[data-synth-modulator-output]'),
    synthGainInput: root.querySelector('[data-synth-gain-input]'),
    synthGainOutput: root.querySelector('[data-synth-gain-output]'),
    synthCutoffInput: root.querySelector('[data-synth-cutoff-input]'),
    synthCutoffOutput: root.querySelector('[data-synth-cutoff-output]'),
    synthResonanceInput: root.querySelector('[data-synth-resonance-input]'),
    synthResonanceOutput: root.querySelector('[data-synth-resonance-output]'),
    synthWaveformInput: root.querySelector('[data-synth-waveform-input]'),
    synthWaveformOutput: root.querySelector('[data-synth-waveform-output]'),
    synthDistortionInput: root.querySelector('[data-synth-distortion-input]'),
    synthDistortionOutput: root.querySelector('[data-synth-distortion-output]'),
    synthMapButtons: Array.from(root.querySelectorAll('[data-synth-map-capture]')),
    synthCurveButtons: Array.from(root.querySelectorAll<HTMLButtonElement>('[data-synth-curve]')),
    sessionLeaderField: root.querySelector('[data-session-leader-field]'),
    sessionLeaderSelect: root.querySelector('[data-session-leader-select]'),
    mixerSynthGainInput: root.querySelector('[data-mixer-synth-gain]'),
    mixerSynthMeter: root.querySelector('[data-mixer-meter="synth"]'),
    mixerSynthMuteButton: root.querySelector('[data-mixer-synth-mute]'),
    mixerSynthPanInput: root.querySelector('[data-mixer-synth-pan]'),
    mixerSynthPanKnob: root.querySelector('[data-mixer-synth-pan-knob]'),
    mixerSynthReverbSendInput: root.querySelector('[data-mixer-synth-reverb-send]'),
    mixerSynthReverbSendKnob: root.querySelector('[data-mixer-synth-reverb-send-knob]'),
    mixerSynthDelaySendInput: root.querySelector('[data-mixer-synth-delay-send]'),
    mixerSynthDelaySendKnob: root.querySelector('[data-mixer-synth-delay-send-knob]'),
    mixerBallGainInput: root.querySelector('[data-mixer-ball-gain]'),
    mixerBallMeter: root.querySelector('[data-mixer-meter="ball"]'),
    mixerBallMuteButton: root.querySelector('[data-mixer-ball-mute]'),
    mixerBallPanInput: root.querySelector('[data-mixer-ball-pan]'),
    mixerBallPanKnob: root.querySelector('[data-mixer-ball-pan-knob]'),
    mixerBallReverbSendInput: root.querySelector('[data-mixer-ball-reverb-send]'),
    mixerBallReverbSendKnob: root.querySelector('[data-mixer-ball-reverb-send-knob]'),
    mixerBallDelaySendInput: root.querySelector('[data-mixer-ball-delay-send]'),
    mixerBallDelaySendKnob: root.querySelector('[data-mixer-ball-delay-send-knob]'),
    mixerIncomingGainInput: root.querySelector('[data-mixer-incoming-gain]'),
    mixerIncomingMeter: root.querySelector('[data-mixer-meter="incoming"]'),
    mixerIncomingMuteButton: root.querySelector('[data-mixer-incoming-mute]'),
    mixerIncomingPanInput: root.querySelector('[data-mixer-incoming-pan]'),
    mixerIncomingPanKnob: root.querySelector('[data-mixer-incoming-pan-knob]'),
    mixerIncomingReverbSendInput: root.querySelector('[data-mixer-incoming-reverb-send]'),
    mixerIncomingReverbSendKnob: root.querySelector('[data-mixer-incoming-reverb-send-knob]'),
    mixerIncomingDelaySendInput: root.querySelector('[data-mixer-incoming-delay-send]'),
    mixerIncomingDelaySendKnob: root.querySelector('[data-mixer-incoming-delay-send-knob]'),
    mixerHpGainInput: root.querySelector('[data-mixer-hp-gain]'),
    mixerHpMeter: root.querySelector('[data-mixer-meter="hp"]'),
    mixerHpMuteButton: root.querySelector('[data-mixer-hp-mute]'),
    mixerHpPanInput: root.querySelector('[data-mixer-hp-pan]'),
    mixerHpPanKnob: root.querySelector('[data-mixer-hp-pan-knob]'),
    mixerHpReverbSendInput: root.querySelector('[data-mixer-hp-reverb-send]'),
    mixerHpReverbSendKnob: root.querySelector('[data-mixer-hp-reverb-send-knob]'),
    mixerHpDelaySendInput: root.querySelector('[data-mixer-hp-delay-send]'),
    mixerHpDelaySendKnob: root.querySelector('[data-mixer-hp-delay-send-knob]'),
    mixerMasterGainInput: root.querySelector('[data-mixer-master-gain]'),
    mixerMasterMeter: root.querySelector('[data-mixer-meter="master"]'),
    mixerMasterMuteButton: root.querySelector('[data-mixer-master-mute]'),
    mixerMasterPanInput: root.querySelector('[data-mixer-master-pan]'),
    mixerMasterPanKnob: root.querySelector('[data-mixer-master-pan-knob]'),
    mixerVideoLumaInput: root.querySelector('[data-mixer-video-luma]'),
    mixerVideoLumaKnob: root.querySelector('[data-mixer-video-luma-knob]'),
    mixerVideoTintInput: root.querySelector('[data-mixer-video-tint]'),
    mixerVideoTintKnob: root.querySelector('[data-mixer-video-tint-knob]'),
    mixerVideoSaturationInput: root.querySelector('[data-mixer-video-saturation]'),
    mixerVideoSaturationKnob: root.querySelector('[data-mixer-video-saturation-knob]'),
    mixerVideoContrastInput: root.querySelector('[data-mixer-video-contrast]'),
    mixerVideoContrastKnob: root.querySelector('[data-mixer-video-contrast-knob]'),
    mixerVideoBrightnessInput: root.querySelector('[data-mixer-video-brightness]'),
    mixerVideoBrightnessKnob: root.querySelector('[data-mixer-video-brightness-knob]'),
    videoBypassToggleButton: root.querySelector('[data-video-bypass-toggle]'),
    mixerResetButtonNodes: Array.from(root.querySelectorAll('[data-mixer-reset-button]')),
    mixerResetScopeNodes: Array.from(root.querySelectorAll('[data-mixer-reset-scope]')),
    mixerResetControlNodes: Array.from(root.querySelectorAll('[data-mixer-reset-control]')),
    summaryActionButtons: Array.from(root.querySelectorAll('[data-summary-action]')),
    synthReverbTimeInput: root.querySelector('[data-synth-reverb-time-input]'),
    synthReverbTimeOutput: root.querySelector('[data-synth-reverb-time-output]'),
    synthReverbMixInput: root.querySelector('[data-synth-reverb-mix-input]'),
    synthReverbMixOutput: root.querySelector('[data-synth-reverb-mix-output]'),
    synthDelayTimeInput: root.querySelector('[data-synth-delay-time-input]'),
    synthDelayTimeOutput: root.querySelector('[data-synth-delay-time-output]'),
    synthDelayFeedbackInput: root.querySelector('[data-synth-delay-feedback-input]'),
    synthDelayFeedbackOutput: root.querySelector('[data-synth-delay-feedback-output]'),
    synthDelayMixInput: root.querySelector('[data-synth-delay-mix-input]'),
    synthDelayMixOutput: root.querySelector('[data-synth-delay-mix-output]'),
    synthDelayToneInput: root.querySelector('[data-synth-delay-tone-input]'),
    synthDelayToneOutput: root.querySelector('[data-synth-delay-tone-output]'),
    synthCompToggle: root.querySelector('[data-synth-comp-toggle]'),
    synthCompThresholdInput: root.querySelector('[data-synth-comp-threshold-input]'),
    synthCompThresholdOutput: root.querySelector('[data-synth-comp-threshold-output]'),
    synthCompRatioInput: root.querySelector('[data-synth-comp-ratio-input]'),
    synthCompRatioOutput: root.querySelector('[data-synth-comp-ratio-output]'),
    synthCompAttackInput: root.querySelector('[data-synth-comp-attack-input]'),
    synthCompAttackOutput: root.querySelector('[data-synth-comp-attack-output]'),
    synthCompReleaseInput: root.querySelector('[data-synth-comp-release-input]'),
    synthCompReleaseOutput: root.querySelector('[data-synth-comp-release-output]'),
    synthCompKneeInput: root.querySelector('[data-synth-comp-knee-input]'),
    synthCompKneeOutput: root.querySelector('[data-synth-comp-knee-output]'),
    synthLimiterToggle: root.querySelector('[data-synth-limiter-toggle]'),
    synthLimiterThresholdInput: root.querySelector('[data-synth-limiter-threshold-input]'),
    synthLimiterThresholdOutput: root.querySelector('[data-synth-limiter-threshold-output]'),
    synthLimiterReleaseInput: root.querySelector('[data-synth-limiter-release-input]'),
    synthLimiterReleaseOutput: root.querySelector('[data-synth-limiter-release-output]'),
  };
};
