import type { TuningSpec, MidiTuningRow } from '../../types/tuning';

export const exportTun = (spec: TuningSpec, table: MidiTuningRow[]): string => {
  const lines: string[] = [];
  lines.push('; Microtonal Tuning Archive');
  lines.push('; Generated by Musiki - Centauro Pod');
  lines.push(`; Source syntax: ${spec.sourceText}`);
  lines.push('');
  lines.push('[Info]');
  lines.push(`Name = ${spec.name}`);
  lines.push('Author = Musiki Centauro');
  lines.push('Symmetric = No');
  lines.push('');
  lines.push('[Keyboard]');
  lines.push(`BaseNote = ${spec.baseMidi}`);
  lines.push(`BaseFreq = ${spec.baseFreq.toFixed(6)}`);
  lines.push('');
  lines.push('[Map]');

  for (const row of table) {
    lines.push(`Note ${row.midi} = ${row.frequency.toFixed(6)}`);
  }

  return lines.join('\r\n');
};
